camtours/camtours/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from employee import views as employee_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls')),

]

camtours/employee/urls.py
from django.conf.urls import include, url
from django.urls import path
from employee import views as employee_view
from employee.views import *
from django.conf import settings 
from django.conf.urls.static import static

from employee.views import *


app_name = 'employee'
urlpatterns = [
    # url('^employee/detail', employee_view.detail),
    # url('^employee/', employee_view.index),

    # url('^employee', employee_view.index),
    # url('^employee/detail', employee_view.detail),

    # url('^$', employee_view.index, name='homepage'),
    url('^$', IndexView.as_view(), name='homepage'),
    url('^(?P<id>\d+)/(?P<name>\D+)/$', employee_view.show_employee_detail, name="employee_detail"),
    # url('^detail/$', employee_view.detail, name='detail'),
    url('^detail/$', detail.as_view(), name='detail'),
]

camtours/employee/models.py
from statistics import mode
from django.db import models

GENDER = (
    ('MALE', 'M'),
    ('FEMALE', 'F'),
)
class Employee(models.Model): 
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=120)
    sex = models.CharField(max_length=7, choices=GENDER)
    dob = models.DateTimeField(auto_created=False)
    email = models.EmailField(max_length=150)
    tel = models.CharField(max_length=20)
    address = models.TextField()
    status = models.BooleanField()
    def __str__(self):
        return str(self.first_name) + " " + str(self.last_name) 

camtours/employee/views.py
from django.shortcuts import render
from employee.models import Employee
from django.views.generic import View, TemplateView 
from django.views import generic
from django.core.paginator import Paginator


# Create your views here.
# def index(request): 
#     # data = ["Student A", "Student B", "Student C", "Student D", "Student E"]
#     data = Employee.objects.filter() # SELECT * FROM Employee
#     return render(request, 'main/index.html', {'data': data})


class IndexView(generic.ListView): 
    template_name =  'main/index.html'
    context_object_name = 'data'
    paginate_by = 2
    def get_queryset(self):
        return Employee.objects.filter().order_by('-id')

    

# def detail(request): 
#     return render(request, 'employee/index.html')
# class detail(TemplateView):
#     template_name = 'employee/index.html'
#     def get_context_data(self, **kwargs):
#         return super(detail, self).get_context_data(**kwargs)
#         context['data']: 'Hello world'
#         return context

class detail(View): 
    template_name = 'employee/index.html'

    def dispatch(self, request, *args, **kwargs):
        print("Loading dispatching")
        return super().dispatch(request, *args, **kwargs)
   
    def get(self, request): 
        print("Hello world")
        data = Employee.objects.filter()
        print(data)
        return render(request, self.template_name, {'data': 'test'})
    
    def post(self, request):
        print("POST ME FROM FORM")
        return render(request, self.template_name, {'data': 'test'})


def show_employee_detail(request, id, name): 
    id = id
    # var1 = request.GET['var1']
    # print("Extra parameter is: ", var1)
    data = Employee.objects.filter(id=id) # SELECT * FROM Employee WHERE id = 1
    return render(request, 'employee/show_employee_detail.html', {'data': data})

camtours/camtours/templates/employee/index.html
{% extends 'main/main.html' %}
{% block title %} Employee {% endblock title %}

{% block content %} 
    <h1>Employee Page</h1>
{% endblock %}

camtours/camtours/templates/employee/show_employee_detail.html
{% extends '../main/main.html' %}
{% block title %} Employee {% endblock title %}

{% block content %} 
    {{ data }}
{% endblock %}

camtours/camtours/templates/main/index.html
{% extends 'main/main.html' %}

{% block title %}Home{% endblock title %}
{% block style %}
<style type="text/css">
    .sub_box
    {
        width: 100%;
        height: 180px;
        border: 1px solid gray;
        box-shadow: 5px 5px gray;

    }
</style>
{% endblock style %}
{% block content %}


    <div class="container">
        <h1>Welcome to Camtours</h1>
    </div>

    <div class="container">
        <div class="row">
            {% if data %}
                {% for i in data %}
                    <div class="col-md-3">
                        <!-- <a href="/employee/{{ i.id }}/?var1={{ i.first_name }} {{ i.last_name }}"> -->
                        <a href="{% url 'employee:employee_detail' i.id i.first_name %}">   
                            <div class="sub_box">
                                {{ i.first_name }} {{ i.last_name }}
                            </div>
                        </a>
                    </div>
                {% endfor %}
            {% else %}
                <div>
                    <h1>No data retrieved</h1>
                </div>
            {% endif %}
        </div>

        <div class="pagination_index">
        
            {% if is_paginated %}
            <hr>
                <ul class="pagination" style="margin:0px 0px !important">
                {% if page_obj.has_previous %}
                    <li>
                        <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
                    </li>
                {% endif %}
                    <li class="">
                        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                    </li>
                {% if page_obj.has_next %}
                    <li>
                        <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
                    </li>
                {% endif %}
                </ul>
            
            {% endif %}
        </div>

    </div>
{% endblock content %}
    

camtours/camtours/templates/main/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Myhome {% endblock title %}</title>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
 
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    {% block style %} {% endblock style %}
</head>
<body>
    <header></header>
    <main>
        <div>
           
            {% block content %}

            {% endblock content %}
        </div>
       

        <footer>
            <div style = "width: 100%; height: 100px; background-color: black;">
                <span style="color:white;">@GreatX, All right reserved.</span>
            </div>
        </footer>
       
    </main>
</body>
</html>